// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestDeployedRModels.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class InputParameters
    {
        /// <summary>
        /// Initializes a new instance of the InputParameters class.
        /// </summary>
        public InputParameters() { }

        /// <summary>
        /// Initializes a new instance of the InputParameters class.
        /// </summary>
        public InputParameters(double? hp = default(double?), double? wt = default(double?))
        {
            Hp = hp;
            Wt = wt;
        }

        /// <summary>
        /// numeric
        /// </summary>
        [JsonProperty(PropertyName = "hp")]
        public double? Hp { get; set; }

        /// <summary>
        /// numeric
        /// </summary>
        [JsonProperty(PropertyName = "wt")]
        public double? Wt { get; set; }

    }
}
