// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestDeployedRModels.Models
{
    using Newtonsoft.Json;

    public partial class OutputParameters
    {
        /// <summary>
        /// Initializes a new instance of the OutputParameters class.
        /// </summary>
        public OutputParameters() { }

        /// <summary>
        /// Initializes a new instance of the OutputParameters class.
        /// </summary>
        public OutputParameters(double? answer = default(double?))
        {
            Answer = answer;
        }

        /// <summary>
        /// numeric
        /// </summary>
        [JsonProperty(PropertyName = "answer")]
        public double? Answer { get; set; }

    }
}
