// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestDeployedRModels.Models
{
    using Newtonsoft.Json;

    public partial class RenewTokenRequest
    {
        /// <summary>
        /// Initializes a new instance of the RenewTokenRequest class.
        /// </summary>
        public RenewTokenRequest() { }

        /// <summary>
        /// Initializes a new instance of the RenewTokenRequest class.
        /// </summary>
        public RenewTokenRequest(string refreshToken = default(string))
        {
            RefreshToken = refreshToken;
        }

        /// <summary>
        /// A currently valid refresh token.
        /// </summary>
        [JsonProperty(PropertyName = "refreshToken")]
        public string RefreshToken { get; set; }

    }
}
