// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestDeployedRModels.Models
{
    using Newtonsoft.Json;

    public partial class StartBatchExecutionResponse
    {
        /// <summary>
        /// Initializes a new instance of the StartBatchExecutionResponse
        /// class.
        /// </summary>
        public StartBatchExecutionResponse() { }

        /// <summary>
        /// Initializes a new instance of the StartBatchExecutionResponse
        /// class.
        /// </summary>
        public StartBatchExecutionResponse(string batchExecutionId = default(string))
        {
            BatchExecutionId = batchExecutionId;
        }

        /// <summary>
        /// Id of the asynchronous execution.
        /// </summary>
        [JsonProperty(PropertyName = "batchExecutionId")]
        public string BatchExecutionId { get; set; }

    }
}
